### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by davidkwong** [mattstyles/yeoman-angular-express-plus#2]
Hello,

I am new to nodejs and the socket io library . After I run the server, I check the console.

There is an error. Is it normal ? Do you have a quick tutorial on how to set up or is it an issue ??

GET http://localhost:9000/socket.io/1/?t=1369403812532 404 (Not Found)

**Comment by mattstyles** [comment]
Hi David, sorry I'm on the run again but the grunt server task just runs a 'generic' server that'll fire the front end, meaning sockets and database will fail because there is no 'real' backend running them. I need to make this more clear in the documentation. If you run `grunt prod --use` then it'll build the project (including the backend) and spark up the server so you'll get the sockets back end. 

Use `grunt prod --open-server` again if you just want to spark up the server without rebuilding the project. Optionally you could run `node server/server` to fire it into action. 

Gonna stick better documentation on the roadmap as this is the result of poor communication on my part. 

I've got another repo called [Hermes](https://github.com/mattstyles/hermes) which shows an example of using this project seed in a project that uses sockets. Might be of interest to you. I'm in the process of writing a blog post about it at the moment so if you are interested I'll keep you posted. 

Sorry for the quick reply, still on the move at the moment with a group of 2 year olds! ( don't ask ). I'll elaborate later if necessary (on the task, not the 2 years olds)! 
—

**Comment by davidkwong** [comment]
I guess I have to brush up my skills =D

**Comment by ruslango** [comment]
hi, i have a problem with  grunt dev. After i run  grunt dev, i see  'Not Connected to Server' on my page, and routs don't work, can u help me? I'm on master brunch

**Comment by mattstyles** [comment]
This is where I REALLY need to sort out the docs because this is a tad unintuitive.

So, `grunt dev` opens up ONLY the client-side, there's no real backend (nothing from the project) so express routes, db, sockets wont be active.  The advantage is that the watch task is running which allows you to develop the client-side and have that watch task update your project as it is running.

Use `grunt dev --use-server` to fire up the project using the _real_ backend.

It is possible your browser will open before your server, so check your terminal to make sure the server has started and hit refresh.  Any changes to the server code will require restarting the server and client-side changes just need a refresh.

**Comment by ruslango** [comment]
thx a lot ! =)
