### ISSUE TITLE
Port differences

### ISSUE THREAD

**Issue by sjclemmy** [mattstyles/yeoman-angular-express-plus#5]
Hi, Probably my noobness, but when you run grunt server it runs on port 9000, with no socket connection. However if you run the server manually and link to port 3001 as mentioned in the app-config.json file it connects correctly.

**Comment by mattstyles** [comment]
Hi, sorry, thought I had replied to this last night!  

Port 9000 is the 'dummy' livereload server that is a 'dumb' server just pushing the app code.  Hitting up `grunt server` is only running the dummy server, the advantage being that you can work on the client side and have reloading.

I'm currently looking at solutions to get a livereload of the actual server code, the problem is that it has to be quick enough to be beneficial so just working through that at the moment.

The 'actual' server runs on port 3001 (or whatever is specified in the config).  With the actual server you get all your actual backend code (routes, sockets, db) but dont get the livereload.

The naming of `grunt server` is misleading given that there is an actual server packaged in the project.  It needs changing to be more intuitive.

If you run `grunt server --use-server` (or `grunt dev --use-server`) it'll fire up the actual server rather than the livereload 'dummy' server.

**Comment by sjclemmy** [comment]
Thanks for the response -  my lack of knowledge shining through here, I've still getting my head around this stack and using grunt etc. I think I was confused by the `grunt server` command, assuming it was running the server. I'll get back to my tutorials....

**Comment by mattstyles** [comment]
No, you're right, it is confusing, and the lack of detailed documentation doesn't help!!  It's from when the project was front-end only, I'll change the naming to `grunt dev` for front-end with a `grunt dev --reload` option and have `grunt server` just build and open the server, should make things much more intuitive.
