### ISSUE TITLE
Grunt server: client can't GET anything except the main page.

### ISSUE THREAD

**Issue by d4goxn** [mattstyles/yeoman-angular-express-plus#6]
After cloning and installing the express branch, `grunt dev` opens a browser window to the index page, which works, but the route `/route` returns an express error page. When node is started manually (`cd server && node server.js`), the `/route` route works.

This also affects the sockets and mongo branches. GET `http://localhost:9000/socket.io/1/?t=13755960810841` returns a 404. When starting the server manually, sockets, database and routes all work.

PS Thank you for creating this awesome seed! There are a lot of goodies in here that I am not very experienced with, but I am exploring and learning :)
- Dan

**Comment by mattstyles** [comment]
Yeah, that's a poor naming convention on my part and something that should really be changed.

`grunt server` opens a live-reload server that only serves the frontend section of the project, in order to use the backend you need to use `grunt server --use-server` (or `grunt server --restart-server`), or manually fire up `node server/server` and point your browser to `localhost:3001` as you have done.

I normally use `grunt dev` which is an alias for `grunt server` so I reckon that should be the norm for just the front-end livereload shizzle and `grunt server` can become what `grunt server --use-server` is now i.e. running the project backend.

If you run `grunt -h` there’s info on all the current `grunt` tasks.
